import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  // title: " DARUT TAQWA 4 MODOPURO MOOSARI",
  // description: "Generated by create next app",
  metadataBase: new URL(
    process.env.NEXT_PUBLIC_SITE_URL || "http://daruttaqwa4.entercel.com/",
  ),
  title: {
    default: "Yayasan Darut Taqwa IV Modopuro Mojokerto",
    template: "%s | Darut Taqwa 4",
  },
  description:
    "Yayasan Darut Taqwa IV Modopuro Mojokerto — mengelola empat lembaga pendidikan: Pondok, Madin, TPQ, dan Tahfidz. Membentuk generasi yang berakhlak mulia, berilmu, dan bermanfaat bagi umat.",
  keywords: [
    "yayasan darut taqwa",
    "darut taqwa 4",
    "modopuro",
    "mojokerto",
    "pendidikan agama",
    "pondok pesantren",
    "madin",
    "tpq",
    "tahfidz",
    "santri",
  ],
  authors: [{ name: "Yayasan Darut Taqwa IV" }],
  openGraph: {
    type: "website",
    locale: "id_ID",
    url: process.env.NEXT_PUBLIC_SITE_URL || "http://daruttaqwa4.entercel.com/",
    siteName: "Yayasan Darut Taqwa IV",
    title: "Darut Taqwa IV Modopuro Mojokerto",
    description:
      "Yayasan Darut Taqwa IV Modopuro Mojokerto — mengelola empat lembaga pendidikan: Pondok, Madin, TPQ, dan Tahfidz.",
    images: [
      {
        url: "/og.jpg",
        width: 1200,
        height: 630,
        alt: "Darut Taqwa IV",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Darut Taqwa IV Modopuro Mojokerto",
    description:
      "Yayasan Darut Taqwa IV Modopuro Mojokerto — mengelola empat lembaga pendidikan: Pondok, Madin, TPQ, dan Tahfidz.",
  },
  robots: {
    index: true,
    follow: true,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Header />
        {children}
        <div className="cointaner mx-auto px-4"></div>
      </body>
    </html>
  );
}
